import Head from 'next/head'
import Image from 'next/image'
import Grid from '../components/grid'
import UploadImgModal from '@/components/uploadImgModal'
import { useState } from 'react'



export default function Home() {

  const [uploadModalOpen,setUploadModalOpen] = useState(false)
  const [filterText,setFilterText] = useState("")

  return (
    <>
      <Head>
        <title>Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-10 items-center mt-10">
        {/* Heading */}
        <h1 className="font-bold text-4xl">Image Gallery</h1>

        {/* Search and add button */}
        <div className="flex gap-4 items-center sm:flex-row flex-col">
          <input type="text" placeholder='Search image...' value={filterText} onChange={(e)=>setFilterText(e.target.value)} />
          <p className='underline'>OR</p>
          <button onClick={()=>setUploadModalOpen(true)}>Add a image</button>
        </div>

        {/* Images */}
        <Grid filterText={filterText} />

        {/* Lightbox */}
        { uploadModalOpen && <UploadImgModal setUploadModalOpen={setUploadModalOpen} />}
      </main>
    </>
  )
}
